Repository Tek-Pheed/AREA, pull requests merged in 2024-10, with the labels that each got.

#123 MERGE: AREA-98 CI/CD WS
  .github/workflows/area-api.yml
  .github/workflows/area-ws.yml
Labels: CI / CD

#122 MERGE: AREA-99 CI/CD Website
  .github/workflows/area-web.yml
  area/assets/icon-only.jpg
Labels: CI / CD

#121 MERGE: AREA-114-profile-page-redesign into dev
  area/src/app/components/application_connection/app-connection.components.html
  area/src/app/components/application_connection/app-connection.components.scss
  area/src/app/components/dashboard_cards/dashboard_cards.components.scss
  area/src/app/components/profil_card/profil_card.components.html
  area/src/app/components/profil_card/profil_card.components.scss
  area/src/app/components/profil_card/profil_card.components.ts
  area/src/app/profil/profile.page.html
  area/src/app/profil/profile.page.scss
Labels: enhancement

#128 MERGE: Area 116 fix front bugs into dev
  area/src/app/components/editor_settings/editor_settings.components.html
  area/src/app/components/editor_settings/editor_settings.components.ts
  area/src/app/components/editor_swap_settings/editor_swap_settings.components.html
  area/src/app/components/editor_swap_settings/editor_swap_settings.components.scss
  area/src/app/components/editor_swap_settings/editor_swap_settings.components.ts
  area/src/app/components/navbar/navbar.components.html
  area/src/app/components/navbar/navbar.components.scss
  area/src/app/components/navbar/navbar.components.ts
  area/src/app/components/profil_card/profil_card.components.html
  area/src/app/components/profil_card/profil_card.components.scss
  area/src/app/components/profil_card/profil_card.components.ts
  area/src/app/dashboard/dashboard.page.html
  area/src/app/dashboard/dashboard.page.scss
  area/src/app/dashboard/dashboard.page.ts
  area/src/app/profil/profile.page.html
  area/src/app/profil/profile.page.ts
  area/src/app/utils/data.models.ts
Labels: bug, enhancement

#131 MERGE: Area 116 fix front bugs into dev
  area/src/app/components/editor_swap_settings/editor_swap_settings.components.scss
  area/src/app/integrations/integrations.page.html
  area/src/app/integrations/integrations.page.scss
Labels: bug

#132 FIX: profile image missing
  area/src/app/components/navbar/navbar.components.ts
  area/src/app/profil/profile.page.ts
Labels: bug

#133 FIX: profile image typo
  area/src/app/components/navbar/navbar.components.ts
  area/src/app/profil/profile.page.ts
Labels: bug

#134 Area 116 fix front bugs
  area/src/app/components/dashboard_cards/dashboard_cards.components.scss
  area/src/app/components/profil_card/profil_card.components.html
  area/src/app/components/profil_card/profil_card.components.scss
  area/src/app/components/profil_card/profil_card.components.ts
  area/src/app/profil/profile.page.html
  area/src/app/profil/profile.page.ts
  area/src/app/utils/data.models.ts
Labels: enhancement

#135 FIX: button service connection
  area/src/app/components/application_connection/app-connection.components.html
Labels: bug

#138 ADD: stylising animation to edit the profil image
  area/src/app/components/profil_card/profil_card.components.html
  area/src/app/components/profil_card/profil_card.components.scss
Labels: enhancement

#141 MERGE: Area 121 ajustements front
  area/src/app/components/application_connection/app-connection.components.html
  area/src/app/components/navbar/navbar.components.scss
  area/src/app/login/login.page.html
Labels: bug

#142 FIX: refresh token null
  api/src/routes/oauth/oauth.query.ts
Labels: bug

#143 UPDATE: profile image effects
  area/src/app/components/profil_card/profil_card.components.scss
  area/src/app/components/profil_card/profil_card.components.ts
Labels: bug, enhancement

#146 MERGE: Area 121 ajustements front into dev
  area/src/app/components/dashboard_cards/dashboard_cards.components.scss
  area/src/app/login/login.page.html
  area/src/app/login/login.page.scss
  area/src/app/register/register.page.html
  area/src/app/register/register.page.scss
Labels: enhancement

#147 MERGE: Area 121 ajustements front into dev
  area/src/app/login/login.page.html
  area/src/app/login/login.page.scss
  area/src/app/login/login.page.ts
  area/src/app/register/register.page.html
  area/src/app/register/register.page.scss
  area/src/app/register/register.page.ts
Labels: bug, enhancement

#148 MERGE: AREA-94 Faire la connexion aux apis
  api/package.json
  api/src/routes/discord/discord.ts
  api/src/routes/github/github.ts
  api/src/routes/google/google.ts
  api/src/routes/spotify/spotify.ts
  api/src/routes/twitch/twitch.ts
  api/src/routes/unsplash/unsplash.ts
  area/assets/icon-background.jpg
  area/assets/icon-foreground.jpg
  area/capacitor.config.ts
  area/package.json
  area/src/app/app.component.ts
  area/src/app/components/application_connection/app-connection.components.ts
  area/src/app/profil/profile.page.scss
  area/src/assets/icons/icon-128.webp
  area/src/assets/icons/icon-192.webp
  area/src/assets/icons/icon-256.webp
  area/src/assets/icons/icon-48.webp
  area/src/assets/icons/icon-512.webp
  area/src/assets/icons/icon-72.webp
  area/src/assets/icons/icon-96.webp
  area/src/manifest.webmanifest
  area/src/utils/api.services.ts
  ws/package.json
Labels: bug, enhancement, CI / CD

#149 UPDATE: navbar image
  area/src/app/components/navbar/navbar.components.scss
Labels: enhancement

#152 MERGE: AREA-123 Crash webservice when refresh token is null
  api/package.json
  area/package.json
  ws/package.json
  ws/src/apis/twitch/actions.ts
  ws/src/core/actions/twitch.actions.ts
Labels: bug

#155 MERGE: Area 118 bonus plusieurs reactions into dev
  api/src/routes/user/configs/configs.query.ts
  area/src/app/components/action_cards/actions_cards.components.html
  area/src/app/components/action_cards/actions_cards.components.scss
  area/src/app/components/action_cards/actions_cards.components.ts
  area/src/app/components/editor_settings/editor_settings.components.html
  area/src/app/components/editor_settings/editor_settings.components.ts
  area/src/app/components/editor_swap_settings/editor_swap_settings.components.html
  area/src/app/components/editor_swap_settings/editor_swap_settings.components.ts
  area/src/app/dashboard/dashboard.page.ts
  area/src/app/editeur/editeur.page.html
  area/src/app/editeur/editeur.page.scss
  area/src/app/editeur/editeur.page.spec.ts
  area/src/app/editeur/editeur.page.ts
  area/src/app/integrations/integrations.page.ts
  area/src/app/profil/profile.page.ts
  area/src/app/utils/data.models.ts
  area/src/assets/icon/favicon.png
  ws/src/apis/twitch/actions.ts
  ws/src/apis/twitch/reactions.ts
  ws/src/core/reaction.manager.ts
  ws/src/core/reactions/nexus.reactions.ts
  ws/src/utils/data.model.ts
  ws/src/utils/refresh.ts
Labels: enhancement

#162 MERGE: Area 126 front bugfix into dev
  area/src/app/editeur/editeur.page.ts
Labels: bug

#163 MERGE: Profil dashboard multiple redirection
  api/src/routes/discord/discord.ts
  api/src/routes/github/github.ts
  api/src/routes/google/google.ts
  api/src/routes/spotify/spotify.ts
  api/src/routes/twitch/twitch.ts
  api/src/routes/unsplash/unsplash.ts
  area/src/app/components/application_connection/app-connection.components.ts
  area/src/app/components/navbar/navbar.components.html
  area/src/app/components/navbar/navbar.components.scss
  area/src/app/editeur/editeur.page.scss
  area/src/app/profil/profile.page.ts
  area/src/global.scss
Labels: bug

#172 FIX: editor label variable undefined && text not white in dark mode
  area/src/app/components/navbar/navbar.components.scss
  area/src/app/editeur/editeur.page.ts
Labels: bug, enhancement

#181 MERGE: Area 101 deploy ios app on testflight
  .github/workflows/area-android.yml
  area/.gitignore
  area/capacitor.config.ts
  area/ios/.gitignore
  area/ios/App/ci_scripts/ci_post_clone.sh
Labels: CI / CD

#179 MERGE: AREA-127 Unplash and google login broken
  api/src/routes/google/google.ts
  api/src/routes/spotify/spotify.ts
  api/src/routes/unsplash/unsplash.ts
  ws/src/core/reactions/github.reactions.ts
Labels: bug

#184 MERGE: Fix cli for tests front
  area/karma.conf.js
  area/package.json
Labels: bug

#187 FIX: image margin in profile page mobile
  area/src/app/components/profil_card/profil_card.components.scss
Labels: bug

#188 FIX: cli not stopping
  area/package.json
  area/src/app/dashboard/dashboard.page.spec.ts
Labels: bug

#191 MERGE: deploy web
  .github/workflows/area-web.yml
Labels: CI / CD

#192 MERGE: deploy web
  .github/workflows/area-web.yml
Labels: bug, CI / CD

#185 MERGE: Area 97 faire des tests unitaires sur le ws
  api/src/routes/unsplash/unsplash.ts
  ws/jest.config.js
  ws/src/__test__/action.manager.test.ts
  ws/src/__test__/actions/discord.actions.test.ts
  ws/src/__test__/actions/github.actions.test.ts
  ws/src/__test__/actions/google.actions.test.ts
  ws/src/__test__/actions/spotify.actions.test.ts
  ws/src/__test__/actions/twitch.actions.test.ts
  ws/src/__test__/actions/unsplash.actions.test.ts
  ws/src/__test__/apis/discord/discord.query.test.ts
  ws/src/__test__/apis/github/githb.query.test.ts
  ws/src/__test__/apis/google/google.query.test.ts
  ws/src/__test__/apis/spotify/spotify.query.test.ts
  ws/src/__test__/apis/twitch/actions.test.ts
  ws/src/__test__/apis/twitch/reactions.test.ts
  ws/src/__test__/apis/twitch/twitch.query.test.ts
  ws/src/__test__/apis/unsplash/actions.test.ts
  ws/src/__test__/apis/unsplash/reactions.test.ts
  ws/src/__test__/apis/unsplash/unsplash.query.test.ts
  ws/src/__test__/reaction.manager.test.ts
  ws/src/__test__/reactions/github.reactions.test.ts
  ws/src/__test__/reactions/google.reactions.test.ts
  ws/src/__test__/reactions/nexus.reactions.test.ts
  ws/src/__test__/reactions/spotify.reactions.test.ts
  ws/src/__test__/reactions/twitch.reactions.test.ts
  ws/src/__test__/reactions/unsplash.reactions.test.ts
  ws/src/__test__/refresh.query.test.ts
  ws/src/__test__/refresh.test.ts
  ws/src/__test__/setup.js
  ws/src/apis/discord/actions.ts
Labels: CI / CD

#194 MERGE: Area 130 faire des actions reactions par d faut into dev
  api/src/__test__/presets.test.ts
  api/src/docs/swagger.ts
  api/src/index.ts
  api/src/routes/presets/presets.query.ts
  api/src/routes/presets/presets.ts
  api/src/utils/serverTest.ts
  area/Dockerfile.apk
  area/src/app/components/dashboard_cards/dashboard_cards.components.html
  area/src/app/components/dashboard_cards/dashboard_cards.components.ts
  area/src/app/dashboard/dashboard.page.html
  area/src/app/dashboard/dashboard.page.ts
  area/src/app/editeur/editeur.page.scss
  area/src/app/editeur/editeur.page.ts
  area/src/app/integrations/integrations.page.ts
  area/src/utils/api.services.ts
Labels: enhancement

#195 MERGE: AREA-131
  api/package.json
  api/src/routes/download/download.ts
  area.sql
  area/package.json
  area/src/app/dashboard/dashboard.page.scss
  area/src/app/login/login.page.html
  area/src/app/login/login.page.scss
  area/src/app/login/login.page.ts
  area/src/app/profil/profile.page.html
  area/src/app/profil/profile.page.scss
  area/src/app/profil/profile.page.ts
  area/src/index.html
  area/src/utils/api.services.ts
  package.json
  ws/package.json
Labels: enhancement

#196 MERGE: Area 130 faire des actions reactions par d faut into dev
  area/src/app/editeur/editeur.page.ts
Labels: bug

#197 MERGE: patch of dev
  .github/workflows/area-api.yml
  .github/workflows/area-web.yml
  .github/workflows/area-ws.yml
  api/src/__test__/about.test.ts
  api/src/__test__/logger.test.ts
  api/src/__test__/services.test.ts
  api/src/routes/discord/discord.ts
  api/src/routes/github/github.ts
  api/src/routes/google/google.ts
  api/src/routes/spotify/spotify.ts
  api/src/routes/twitch/twitch.ts
  api/src/routes/unsplash/unsplash.ts
Labels: bug, CI / CD

#200 MERGE: Fix some bugs
  api/Dockerfile
  area/src/app/components/application_connection/app-connection.components.ts
Labels: bug

#201 UPDATE: log volume in docker compose
  api/Dockerfile
  area/src/app/dashboard/dashboard.page.scss
  area/src/app/editeur/editeur.page.scss
  docker-compose.yml
  ws/Dockerfile
Labels: bug, enhancement

#204 MERGE: fix some bugs
  area/src/app/about/about-routing.module.ts
  area/src/app/about/about.page.html
  area/src/app/about/about.page.module.ts
  area/src/app/about/about.page.scss
  area/src/app/about/about.page.ts
  area/src/app/app-routing.module.ts
  area/src/app/dashboard/dashboard.page.spec.ts
  area/src/app/download_apk/download_apk.page.ts
  area/src/utils/api.services.ts
  ws/src/core/action.manager.ts
Labels: bug, enhancement

#215 FIX: editor datetime not being parsed
  area/src/app/editeur/editeur.page.ts
Labels: bug

#216 FIX: github rerun workflow
  ws/src/apis/github/reactions.ts
  ws/src/core/reactions/github.reactions.ts
Labels: bug

#217 MERGE: Area 124 home page redesign
  area/assets/icon-background.jpg
  area/assets/icon-foreground.jpg
  area/assets/icon-only.jpg
  area/src/app/dashboard/dashboard.page.html
  area/src/app/dashboard/dashboard.page.scss
  area/src/app/download_apk/download_apk.html
  area/src/app/download_apk/download_apk.scss
  area/src/app/home/home.page.html
  area/src/app/home/home.page.scss
  area/src/assets/icon/icon-sprite.svg
  area/src/assets/icon/spriiite.svg
  area/src/assets/icon/sprite.png
  area/src/assets/icon/sprite2.png
  area/src/assets/icon/sprite3.png
  area/src/assets/icon/sprite4.png
  area/src/assets/icon/spriteAction.png
  area/src/assets/icon/spriteAction2.png
  area/src/assets/icon/spriteAction3.png
  area/src/assets/icon/spriteAction4.png
  area/src/assets/icon/spriteAction5.png
Labels: enhancement

#221 MERGE: button for mobile
  area/src/app/home/home.page.scss
Labels: enhancement
