Repository Tek-Pheed/AREA, pull requests merged in 2024-11, with the labels that each got.

#223 MERGE: update doc readme
  README.md
  api/README.md
  area/README.md
  ws/README.md
Labels: documentation

#225 MERGE: Area 132 ajouter l id dans les key de stockage du ws
  ws/.gitignore
  ws/src/__test__/action.manager.test.ts
  ws/src/__test__/actions/discord.actions.test.ts
  ws/src/__test__/actions/github.actions.test.ts
  ws/src/__test__/actions/google.actions.test.ts
  ws/src/__test__/actions/spotify.actions.test.ts
  ws/src/__test__/actions/twitch.actions.test.ts
  ws/src/__test__/actions/unsplash.actions.test.ts
  ws/src/__test__/apis/unsplash/actions.test.ts
  ws/src/__test__/reaction.manager.test.ts
  ws/src/__test__/reactions/github.reactions.test.ts
  ws/src/apis/discord/actions.ts
  ws/src/core/action.manager.ts
  ws/src/core/actions/discord.actions.ts
  ws/src/core/actions/github.actions.ts
  ws/src/core/actions/google.actions.ts
  ws/src/core/actions/spotify.actions.ts
  ws/src/core/actions/twitch.actions.ts
  ws/src/core/actions/unsplash.actions.ts
  ws/src/core/reactions/github.reactions.ts
  ws/src/core/webservice.ts
Labels: enhancement

#227 ADD: final test for ws
  ws/package.json
  ws/src/__test__/apis/discord/actions.test.ts
  ws/src/__test__/apis/github/actions.test.ts
  ws/src/__test__/apis/github/reactions.test.ts
  ws/src/__test__/apis/google/actions.test.ts
  ws/src/__test__/apis/google/reactions.test.ts
  ws/src/__test__/apis/spotify/actions.test.ts
  ws/src/__test__/apis/spotify/reactions.test.ts
  ws/src/__test__/apis/twitch/actions.test.ts
  ws/src/apis/twitch/actions.ts
Labels: CI / CD
